### ISSUE TITLE
Compile errors?

### ISSUE THREAD

**Issue by sarahb55** [WorldWideTelescope/wwt-website#12]
Hi - When I try to follow directions on install.md and build the website I get two errors for files not found:

webclient/Default.aspx.cs
webclient/login.aspx.cs

There actually don't seem to be any files in that folder. Any suggestions? I am using VS Community and have tried 2015 and 2013 versions.

**Comment by cecilia-donnelly** [comment]
Hey @sarahb55 and @thewebkid, I'm getting the same errors, along with a couple others.  I'm running Windows 10 and Visual Studio community edition 2015.

I took a screenshot of the errors (see below).  In addition to the two missing files, there are a few others that I'll have to look into.

To try to find the files, I ran `find -name "*.aspx.cs"` and `find -name "*efault"` and `find -name "*ogin"`.  They didn't show up.  I then ran `git log --name-status` and searched in the results.  Neither file appears anywhere in the git history.

Since they aren't in the history, I imagine these might be generated files that should be created as we build the site.  @thewebkid if that's so, do you have any ideas about why they wouldn't be created as expected? 

![screenshot from 2015-10-29 17-41-14](https://cloud.githubusercontent.com/assets/1497818/10834049/49f433ce-7e64-11e5-8015-1b3e84222cea.png)

**Comment by thewebkid** [comment]
Try deleting the /webclient folder. I am headed out of town in an hour but
it sounds like i accidentally checked it in

**Comment by cecilia-donnelly** [comment]
@thewebkid thank you!  That did resolve the missing files errors -- perfect!  I take it that because we're only building the site we don't need the webclient files?  I still have one remaining error (`The type or namespace name 'ServiceRuntime' does not exist in the namespace 'Microsoft.WindowsAzure' (are you missing an assembly reference?)`) but I think it's because I don't yet have Azure SDK, which is mentioned in INSTALL.md.  Getting close on this!

@sarahb55, do let us know if removing the webclient directory allows you to build the site.

**Comment by thewebkid** [comment]
Yeah, you need the azure sdk

**Comment by cecilia-donnelly** [comment]
Serious progress!  I have a (very broken) version of the website running.  I removed some lines in `ConfigReader.cs` because they were giving me errors (removed the references to `Microsoft.WindowsAzure` and to `RoleEnvironment`).  Probably this brokenness is the result of that, so I'll work on the errors separately.  Still great to have the site running locally!

(sorry for the tiny screen -- my VM refuses to get bigger)

![screenshot from 2015-10-30 10-58-49](https://cloud.githubusercontent.com/assets/1497818/10850739/416179b0-7ef5-11e5-9fb4-016bf6ec0582.png)

**Comment by cecilia-donnelly** [comment]
@thewebkid ah, thanks, I was afraid that must be it.  When I try to install the Azure SDK I get a message saying that it  "requires LocalDB to be installed.  You must enable the Microsoft SQL Server Data Tools feature in Visual Studio 2015 to install LocalDB before proceeding."  Initial investigation suggests that the Data Tools feature isn't available for the Visual Studio Community Edition, though?  I'm still looking into it.

**Comment by cecilia-donnelly** [comment]
@thewebkid @sarahb55:

Okay!  I got the Azure SDK and LocalDB installed and the site now builds with no errors! (I replaced the lines that I removed earlier, so the only change is removing the webclient directory).  The local version still looks very broken in the browser, though.  Ron, do you think there's some step I'm missing, perhaps with an Azure connection?  I tried it in IE10 and Firefox 41.0.2, and it doesn't render correctly in either of them.

**Comment by cecilia-donnelly** [comment]
I put in a pull request (#17) with documentation changes that reflect my conversation with @thewebkid today.  Thanks so much for your time today, Ron!  I now have a working local copy and I think we can get @sarahb55 working too.
