### ISSUE TITLE
Update video link on home page to WWT youtube homepage

### ISSUE THREAD

**Issue by sarahb55** [WorldWideTelescope/wwt-website#26]
Hi - Can you edit the link on the home page to the videos to go to the home page of the youtube channel rather than the list of videos.  

https://www.youtube.com/channel/UCjx-BjxGX6vvxALi9ziBfjA/featured

Thanks,

**Comment by kfogel** [comment]
Oh, that sounds like a good idea.  The idea is that the YouTube channel will always be up-to-date, and will always have the most recent videos at the top, so why should we maintain our own page that would just do the same thing (but require manual maintenance)?

**Comment by cecilia-donnelly** [comment]
@kfogel:
I think @sarahb55 means that she wants the link to point to the "Home" tab of the YouTube account instead of the "Videos" tab, which is what it currently does.  We don't currently maintain our own page of videos, I don't think.  Is that right, Sarah?

I think it's a good idea too!  People are more accustomed to seeing a YouTube homepage than landing on the list of videos.

**Comment by kfogel** [comment]
Ah, thank you @cecilia-donnelly .
